local require = GLOBAL.require
local STRINGS = GLOBAL.STRINGS

STRINGS.CHARACTER_TITLES.polter = "The insincerity butcher"
STRINGS.CHARACTER_NAMES.polter = "Polter"
STRINGS.CHARACTER_DESCRIPTIONS.polter = "*Perk 1\n*Perk 2\n*Perk 3"
STRINGS.CHARACTER_QUOTES.polter = "\"I'm Looking for a GOOD WAY TO DIE\""

STRINGS.NAMES.POLTERWEAPON = "Polter's Weapon"
STRINGS.NAMES.POLTERCHIP = "Polter Chip"
STRINGS.NAMES.POLTERCANDY = "Polter Candy"
STRINGS.NAMES.POLTERCANDY_D = "Polter Candy"
STRINGS.NAMES.POLTERPACK = "Polter Pack"

STRINGS.RECIPE_DESC.POLTERCHIP = "POLTERCHIP 레시피 설명"
STRINGS.RECIPE_DESC.POLTERCANDY = "POLTERCANDY 레시피 설명"
STRINGS.RECIPE_DESC.POLTERCANDY_D = "POLTERCANDY 레시피 설명"
STRINGS.RECIPE_DESC.POLTERPACK = "POLTERPACK 레시피 설명"

STRINGS.CHARACTERS.POLTER = require "speech_polter"

STRINGS.NAMES.POLTER = "Polter"